name: ReadMe Microservices

# Run workflow for every push to the `main` branch
on:
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      # Run GitHub Action to sync all OpenAPI files in the repo
      - name: GitHub Action
        uses: readmeio/readme-micro@v1.0.0
        
        with:
          readme-micro: "'**/*.{yaml,yml,json}' --key=${{ secrets.README_MICRO_SECRET }}"